name: Build firmware2

on:
  workflow_dispatch:
    inputs:
      router-model:
        description: "Router model"
        type: choice
        required: true
        default: "ac12g"
        options:
          - "ac12g"
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    container: registry.gitlab.com/hadzhioglu/padavan-ng
    defaults: { run: { shell: bash } }
    steps:
    - uses: actions/checkout@v4

    - name: Get variables
      run: |
        sed -i 's|\r$||g' variables
        . <(cat variables)
        PADAVAN_THEMES="${PADAVAN_THEMES[*]}"
        for v in "${!PADAVAN_@}" "${!CONFIG_@}"; do
          echo "$v=${!v}" >> $GITHUB_ENV
        done

    - name: Set router model
      run: |
        ROUTER_MODEL="${{ github.event.inputs.router-model }}"
        echo "ROUTER_MODEL=$ROUTER_MODEL" >> $GITHUB_ENV
        echo "Using router model: $ROUTER_MODEL"

    - name: Download sources and toolchain
      run: |
        git config --global --add safe.directory '*'
        git clone -b "$PADAVAN_BRANCH" "$PADAVAN_REPO" ${{ github.workspace }}/padavan-ng
        git -C ${{ github.workspace }}/padavan-ng checkout "$PADAVAN_COMMIT"
        wget -qO- "$PADAVAN_TOOLCHAIN_URL" | tar -C ${{ github.workspace }}/padavan-ng --zstd -xf -

    - name: Install themes
      run: |
        if [[ -n "${PADAVAN_THEMES:-}" ]]; then
          git clone --depth 1 -b "$PADAVAN_THEMES_BRANCH" "$PADAVAN_THEMES_REPO" ${{ github.workspace }}/themes
          cp -r ${{ github.workspace }}/themes/common-theme ${{ github.workspace }}/themes/jquery.js ${{ github.workspace }}/padavan-ng/trunk/user/www/n56u_ribbon_fixed

          for theme in $PADAVAN_THEMES; do
            echo "Installing $theme theme"
            cp -r "${{ github.workspace }}/themes/${theme}-theme" ${{ github.workspace }}/padavan-ng/trunk/user/www/n56u_ribbon_fixed
          done
        fi

    - name: Apply patches and configs
      run: |
        WORKSPACE_PATH="${{ github.workspace }}/workspace"
        cp -rv "$WORKSPACE_PATH/$ROUTER_MODEL/trunk/"* "${{ github.workspace }}/padavan-ng/"
        cp "$WORKSPACE_PATH/$ROUTER_MODEL/trunk/.config" "${{ github.workspace }}/padavan-ng/trunk/.config"
        cd "${{ github.workspace }}/padavan-ng"
        for patch_file in "$WORKSPACE_PATH/$ROUTER_MODEL/patches/"*.patch; do
          patch -p1 < "$patch_file"
        done

    - name: Run custom pre-build script
      run: |
        cd "${{ github.workspace }}/workspace"
        [[ -f pre-build2.sh ]] && . pre-build2.sh || :

    - name: Build firmware
      run: |
        cd ${{ github.workspace }}/padavan-ng/trunk
        ./clear_tree.sh
        ./build_firmware.sh

        FW_FILE_NAME="$(find images -type f -regextype posix-extended -iregex ".*\.(trx|bin)$" \
                        -printf "%T@\t%f\n" | sort -V | tail -1 | cut -f2)"
        [[ -n $FW_FILE_NAME ]] || { echo "Firmware file not found"; exit 1; }
        echo "FW_FILE_NAME=$FW_FILE_NAME" >> $GITHUB_ENV

    - name: Run custom post-build script
      run: '[[ -f post-build2.sh ]] && . post-build2.sh || :'

    - name: Prepare artifacts
      run: |
        cp "padavan-ng/trunk/images/$FW_FILE_NAME" .
        echo "BUILD_TIMESTAMP=$(date '+%Y.%m.%d_%H.%M.%S')" >> $GITHUB_ENV

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: padavan-ng_${{ env.CONFIG_VENDOR }}_${{ env.CONFIG_FIRMWARE_PRODUCT_ID }}_${{ env.BUILD_TIMESTAMP }}
        retention-days: 7
        path: |
          ${{ env.FW_FILE_NAME }}
          build.config

    - name: Check firmware size
      run: |
        partitions=padavan-ng/trunk/configs/boards/$CONFIG_VENDOR/$CONFIG_FIRMWARE_PRODUCT_ID/partitions.config
        max_fw_size="$(awk '/Firmware/ { getline; getline; sub(",", ""); print strtonum($2); }' "$partitions")"
        fw_size="$(stat -c %s "$FW_FILE_NAME")"

        if ((fw_size > max_fw_size)); then
          fw_size_fmtd="$(numfmt --grouping "$fw_size") bytes"
          max_fw_size_fmtd="$(numfmt --grouping "$max_fw_size") bytes"
          echo "Firmware size ($fw_size_fmtd) exceeds max size ($max_fw_size_fmtd) for your target device"
          exit 1
        fi
